[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"
watchPatterns = ["server/**"]

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
