[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"
watchPatterns = ["server/**"]

[deploy]
startCommand = "sh -c 'cd server && ./node_modules/.bin/knex migrate:latest && node index.js'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
